# Generated by Django 5.0.4 on 2024-05-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Seat_Quantity', models.IntegerField()),
                ('Date', models.DateField()),
                ('Movie_Name', models.CharField(max_length=200)),
            ],
        ),
    ]
